### ISSUE TITLE
Fix SQLserver container permission errors

### ISSUE THREAD

**Issue by UTXOnly** [TSE-Coders/they-doing-that#12]
**Issue**
* SQLserver can fail to start as the current docker compose file mounts to a local volume on the host

```yaml
    volumes:
      - "./:/var/opt/mssql"
```

**Suggested Fix**
* Mount to Docker volume to resolve permission error:

```yaml
    volumes:
      - "verb-service-data:/var/opt/mssql"
volumes:
  verb-service-data:
```
